name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push client image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/client:${{ github.sha }}

    - name: Build and push server image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/server:${{ github.sha }}

    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        service: ecsService
        cluster: ryansite-cluster
        wait-for-service-stability: true
